[default]
work_dir=w:\Laravel8\CX3
app_name=CX3
barrier_app=C:Windows\notepad.exe
barrier_service_name=

; use the name of a browser listed in the [browsers] section below
browser=firefox
browser_title=Pycharm

; the app can handle up to 4 URLs, url-url4. They can contain $appName which expands to app_name from above
url=https://www.jetbrains.com/pycharm/
url2=http://microsoft.com
url3=https://google.com?
url4=

; format: 	(the following are separated by ' ~ '
;	0		appPath
;	1		appTitle		If it starts with '*' then a 'contains' match is used. '*' is only needed in the 1st char of the title!
;	2		x,y,w,h
;	3		params
;	4		minimised
;	5		before_start_delay,after_start_delay
;	6		app2waitForPathname,app2waitForTitle
[before]
;app0=
;app1=q:\NetBeans\NetBeans-29\bin\netbeans64.exe ~ *Apache NetBeans ~ 575, 5, 1950, 1350 ~ "${workDir}" --console suppress --userdir "${workDir}/netbeans" ~ no
;app2=C:\Program Files\ConEmu\ConEmu64.exe ~ Artisan ~ 1665,955,900,450 ~ -Title "Artisan" -dir "${workDir}" ~ yes ~ 0,0 ~ notepad.exe,notepad
app3=explorer ~ ${app_name} ~ 1450, 630, 1050, 775 ~ "${workDir}" ~ yes
app4=${browser} ~ *${browser_title} ~ 2565, -700, 1800, 1500 ~ --new-window ${url} ${url2} ${url3} ${url4} ~ no

[after]
;app0=C:\Program Files\SQLyog\SQLyog.exe ~ *SQLyog ~ 3350, 300, 2100, 1080 ~ ~ yes
;    app1=${browser} ~ *${browser_title} ~ 2565, -700, 1800, 1500 ~ --new-window ${url} ${url2} ${url3} ${url4}~ no
;app3=${browser} ~ *${browser_title} ~ 2565, -700, 1800, 1500 ~ --new-tab ${url3} ~ no,2
;app4=${workDir}\00 file watcher.bat ~ File watcher ~ 5135, 795, 1270, 620 ~ ~ no
;app5=C:\Program Files (x86)\WinSCP\WinSCP.exe ~ *WinSCP ~ 5135, 50, 1270, 450 ~ phpdev-1 ~ no

[browsers]
brave=C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
chrome=C:\Program Files\Google\Chrome\Application\chrome.exe
firefox=D:\Portable Apps\LiberKey\MyApps\FirefoxPortable\FirefoxPortable.exe
firefox_dev=C:\Program Files\Firefox Developer Edition\firefox.exe
edge=C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
blisk=C:\Users\nick\AppData\Local\Blisk\Application\blisk.exe
